"""baseline schema (consolidates pre-Alembic migration/*.sql)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-08

Baseline-миграция (feature_113). Консолидирует всю схему, ранее набиравшуюся
вручную из migration/<feature>/*.sql, в одну отправную точку Alembic.

Применение:
- Новая пустая БД: `alembic upgrade head` создаёт всю схему с нуля.
- Существующая production-БД: ОДНОКРАТНО `alembic stamp 0001_baseline`
  (без выполнения DDL), т.к. объекты уже созданы прежними .sql.

Идемпотентность: весь DDL написан так, чтобы безопасно отрабатывать и на пустой,
и на уже существующей БД (CREATE TABLE/INDEX IF NOT EXISTS; DO $$ IF NOT EXISTS $$
для FK/констрейнтов/ALTER COLUMN). Это страховка: даже если кто-то выполнит
upgrade на непустой БД, данные не пострадают.

downgrade не поддерживается: откат baseline означал бы DROP всех таблиц с данными.
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


# Порядок важен из-за внешних ключей: users → projects → categories → expenses → ...
BASELINE_SQL = r"""
-- =========================================================
-- users
-- =========================================================
CREATE TABLE IF NOT EXISTS public.users (
    user_id           TEXT PRIMARY KEY,
    created_at        TIMESTAMP DEFAULT now(),
    active_project_id INTEGER
);

-- =========================================================
-- projects
-- =========================================================
CREATE TABLE IF NOT EXISTS public.projects (
    project_id   SERIAL PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE NO ACTION,
    project_name TEXT,
    created_date DATE,
    deleted_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_projects_deleted_cleanup
    ON public.projects (deleted_at)
    WHERE deleted_at IS NOT NULL;

-- =========================================================
-- project_members
-- =========================================================
CREATE TABLE IF NOT EXISTS public.project_members (
    project_id INTEGER NOT NULL REFERENCES public.projects(project_id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL DEFAULT 'editor',
    joined_at  TIMESTAMP DEFAULT now(),
    CONSTRAINT project_members_pkey PRIMARY KEY (project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_members_user_id
    ON public.project_members (user_id);

CREATE INDEX IF NOT EXISTS idx_project_members_project_user
    ON public.project_members (project_id, user_id);

-- =========================================================
-- project_invites
-- =========================================================
CREATE TABLE IF NOT EXISTS public.project_invites (
    token      TEXT PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES public.projects(project_id) ON DELETE CASCADE,
    inviter_id TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    role       VARCHAR(20) DEFAULT 'editor',
    created_at TIMESTAMP DEFAULT now(),
    expires_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_invites_expires_at
    ON public.project_invites (expires_at);

-- =========================================================
-- categories
-- =========================================================
CREATE TABLE IF NOT EXISTS public.categories (
    category_id SERIAL PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    project_id  INTEGER REFERENCES public.projects(project_id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    is_system   BOOLEAN NOT NULL DEFAULT FALSE,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Уникальный индекс категорий: модель ПЕРСОНАЛЬНАЯ — глобальные категории
-- (project_id IS NULL) свои у каждого пользователя, поэтому уникальность по
-- (user_id, COALESCE(project_id,-1), lower(name)). Это соответствует коду
-- (utils/categories.create_category проверяет дубль по user_id) и реальному
-- состоянию production. NB: ранее тут был индекс без user_id (модель «общие
-- категории» из несостоявшегося feature_53) — он не отражал ни код, ни прод.
CREATE UNIQUE INDEX IF NOT EXISTS categories_user_project_name_lower_idx
    ON public.categories (user_id, COALESCE(project_id, -1), LOWER(name));

CREATE INDEX IF NOT EXISTS idx_categories_user_id
    ON public.categories (user_id);

CREATE INDEX IF NOT EXISTS idx_categories_project_id
    ON public.categories (project_id);

-- =========================================================
-- expenses
-- =========================================================
CREATE TABLE IF NOT EXISTS public.expenses (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           TEXT REFERENCES public.users(user_id),
    project_id        INTEGER REFERENCES public.projects(project_id) ON DELETE CASCADE,
    date              DATE,
    "time"            TIME,
    amount            NUMERIC,
    category          TEXT,
    description       TEXT,
    month             INTEGER,
    category_id       INTEGER NOT NULL REFERENCES public.categories(category_id) ON DELETE RESTRICT,
    source_type       TEXT DEFAULT 'manual',
    recurring_rule_id INTEGER,
    created_by_system BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_expenses_category_id
    ON public.expenses (category_id);

CREATE INDEX IF NOT EXISTS idx_expenses_project_id
    ON public.expenses (project_id)
    WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_project_month
    ON public.expenses (project_id, month)
    WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_recurring_rule_id
    ON public.expenses (recurring_rule_id, date)
    WHERE recurring_rule_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_duplicate_lookup
    ON public.expenses (project_id, category_id, date, created_at)
    WHERE project_id IS NOT NULL AND deleted_at IS NULL;

-- =========================================================
-- budgets
-- =========================================================
CREATE TABLE IF NOT EXISTS public.budgets (
    id                     SERIAL PRIMARY KEY,
    user_id                TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    project_id             INTEGER REFERENCES public.projects(project_id) ON DELETE CASCADE,
    amount                 NUMERIC NOT NULL DEFAULT 0,
    month                  INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    year                   INTEGER NOT NULL,
    notify_enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    notify_threshold       NUMERIC,
    last_notified_spending NUMERIC,
    threshold_notified_at  TIMESTAMP,
    overspent_notified_at  TIMESTAMP,
    created_at             TIMESTAMP DEFAULT now(),
    updated_at             TIMESTAMP DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS budgets_personal_uniq
    ON public.budgets (user_id, month, year)
    WHERE project_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS budgets_project_uniq
    ON public.budgets (user_id, project_id, month, year)
    WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS budgets_notify_idx
    ON public.budgets (month, year, notify_enabled)
    WHERE notify_enabled = TRUE;

-- =========================================================
-- recurring_rules (feature_93)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.recurring_rules (
    id                   SERIAL PRIMARY KEY,
    user_id              TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    amount               NUMERIC NOT NULL CHECK (amount > 0),
    category_id          INTEGER NOT NULL REFERENCES public.categories(category_id) ON DELETE RESTRICT,
    comment              TEXT NOT NULL DEFAULT '',
    project_id           INTEGER REFERENCES public.projects(project_id) ON DELETE SET NULL,
    frequency_type       TEXT NOT NULL CHECK (frequency_type IN (
                             'daily', 'every_n_days', 'weekly',
                             'every_n_weeks', 'monthly', 'every_n_months'
                         )),
    interval_value       INTEGER CHECK (interval_value IS NULL OR interval_value >= 1),
    weekday              INTEGER CHECK (weekday IS NULL OR weekday BETWEEN 1 AND 7),
    day_of_month         INTEGER CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31),
    is_last_day_of_month BOOLEAN NOT NULL DEFAULT FALSE,
    start_date           DATE NOT NULL,
    next_run_at          TIMESTAMP NOT NULL,
    status               TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
    created_at           TIMESTAMP NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_interval_for_every_n CHECK (
        frequency_type NOT IN ('every_n_days', 'every_n_weeks', 'every_n_months')
        OR interval_value IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_recurring_rules_next_run
    ON public.recurring_rules (next_run_at)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_recurring_rules_user_id
    ON public.recurring_rules (user_id);

-- expenses.recurring_rule_id ссылается на recurring_rules — добавляем FK после её создания.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_expenses_recurring_rule'
    ) THEN
        ALTER TABLE public.expenses
            ADD CONSTRAINT fk_expenses_recurring_rule
            FOREIGN KEY (recurring_rule_id)
            REFERENCES public.recurring_rules(id) ON DELETE SET NULL;
    END IF;
END $$;

-- =========================================================
-- income_categories / recurring_incomes / incomes (feature_94)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.income_categories (
    income_category_id SERIAL PRIMARY KEY,
    user_id            TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    project_id         INTEGER REFERENCES public.projects(project_id) ON DELETE CASCADE,
    name               VARCHAR(255) NOT NULL,
    is_system          BOOLEAN NOT NULL DEFAULT FALSE,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_income_categories_active_unique_normalized
    ON public.income_categories (
        user_id,
        COALESCE(project_id, -1),
        LOWER(REGEXP_REPLACE(BTRIM(name), '\s+', ' ', 'g'))
    )
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_income_categories_user_id
    ON public.income_categories (user_id);

CREATE INDEX IF NOT EXISTS idx_income_categories_project_id
    ON public.income_categories (project_id);

CREATE TABLE IF NOT EXISTS public.recurring_incomes (
    id                   SERIAL PRIMARY KEY,
    user_id              TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    amount               NUMERIC NOT NULL CHECK (amount > 0),
    income_category_id   INTEGER NOT NULL REFERENCES public.income_categories(income_category_id) ON DELETE RESTRICT,
    comment              TEXT NOT NULL DEFAULT '',
    project_id           INTEGER REFERENCES public.projects(project_id) ON DELETE SET NULL,
    frequency_type       TEXT NOT NULL CHECK (frequency_type IN (
                             'daily', 'every_n_days', 'weekly',
                             'every_n_weeks', 'monthly', 'every_n_months'
                         )),
    interval_value       INTEGER CHECK (interval_value IS NULL OR interval_value >= 1),
    weekday              INTEGER CHECK (weekday IS NULL OR weekday BETWEEN 1 AND 7),
    day_of_month         INTEGER CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31),
    is_last_day_of_month BOOLEAN NOT NULL DEFAULT FALSE,
    start_date           DATE NOT NULL,
    next_run_at          TIMESTAMP NOT NULL,
    status               TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_rec_income_interval_for_every_n CHECK (
        frequency_type NOT IN ('every_n_days', 'every_n_weeks', 'every_n_months')
        OR interval_value IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_recurring_incomes_next_run
    ON public.recurring_incomes (next_run_at)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_recurring_incomes_user_id
    ON public.recurring_incomes (user_id);

CREATE TABLE IF NOT EXISTS public.incomes (
    id                  SERIAL PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    amount              NUMERIC NOT NULL CHECK (amount > 0),
    income_category_id  INTEGER NOT NULL REFERENCES public.income_categories(income_category_id) ON DELETE RESTRICT,
    project_id          INTEGER REFERENCES public.projects(project_id) ON DELETE CASCADE,
    description         TEXT,
    month               INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    income_date         DATE NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    recurring_income_id INTEGER REFERENCES public.recurring_incomes(id) ON DELETE SET NULL,
    created_by_system   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_incomes_project_month
    ON public.incomes (project_id, month)
    WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_incomes_user_month
    ON public.incomes (user_id, month)
    WHERE project_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_incomes_income_date
    ON public.incomes (income_date);

CREATE INDEX IF NOT EXISTS idx_incomes_income_category_id
    ON public.incomes (income_category_id);

CREATE INDEX IF NOT EXISTS idx_incomes_recurring_income_day
    ON public.incomes (recurring_income_id, income_date)
    WHERE recurring_income_id IS NOT NULL;

-- =========================================================
-- cashback: user_cards / cashback_categories / user_cashback_rules (feature_95)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.user_cards (
    id         SERIAL PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    card_name  VARCHAR(255) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_cards_active_name_unique
    ON public.user_cards (
        user_id,
        LOWER(REGEXP_REPLACE(BTRIM(card_name), '\s+', ' ', 'g'))
    )
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_user_cards_user_id
    ON public.user_cards (user_id);

CREATE TABLE IF NOT EXISTS public.cashback_categories (
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    is_global  BOOLEAN NOT NULL DEFAULT FALSE,
    user_id    TEXT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cashback_category_scope CHECK (
        (is_global = TRUE AND user_id IS NULL)
        OR
        (is_global = FALSE AND user_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cashback_categories_global_unique
    ON public.cashback_categories (
        LOWER(REGEXP_REPLACE(BTRIM(name), '\s+', ' ', 'g'))
    )
    WHERE is_global = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_cashback_categories_user_unique
    ON public.cashback_categories (
        user_id,
        LOWER(REGEXP_REPLACE(BTRIM(name), '\s+', ' ', 'g'))
    )
    WHERE is_global = FALSE;

CREATE INDEX IF NOT EXISTS idx_cashback_categories_user_id
    ON public.cashback_categories (user_id);

CREATE TABLE IF NOT EXISTS public.user_cashback_rules (
    id                   SERIAL PRIMARY KEY,
    user_id              TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    user_card_id         INTEGER NOT NULL REFERENCES public.user_cards(id) ON DELETE RESTRICT,
    cashback_category_id INTEGER NOT NULL REFERENCES public.cashback_categories(id) ON DELETE RESTRICT,
    year                 INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2100),
    month                INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    percent              NUMERIC(5, 2) NOT NULL CHECK (percent >= 0 AND percent <= 100),
    created_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_cashback_rule_month UNIQUE (user_card_id, cashback_category_id, year, month)
);

CREATE INDEX IF NOT EXISTS idx_user_cashback_rules_user_month
    ON public.user_cashback_rules (user_id, year, month);

CREATE INDEX IF NOT EXISTS idx_user_cashback_rules_card
    ON public.user_cashback_rules (user_card_id);

-- Сид глобальных категорий кэшбэка (идемпотентно)
INSERT INTO public.cashback_categories(name, is_global, user_id)
VALUES
    ('продукты', TRUE, NULL),
    ('рестораны', TRUE, NULL),
    ('транспорт', TRUE, NULL),
    ('такси', TRUE, NULL),
    ('маркетплейсы', TRUE, NULL),
    ('аптека', TRUE, NULL),
    ('развлечения', TRUE, NULL)
ON CONFLICT DO NOTHING;

-- =========================================================
-- cashback_monthly_snapshots (feature_95)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.cashback_monthly_snapshots (
    id                       SERIAL PRIMARY KEY,
    user_id                  TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    year                     INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2100),
    month                    INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    total_spent              NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_potential_cashback NUMERIC(14, 2) NOT NULL DEFAULT 0,
    effective_spent          NUMERIC(14, 2) NOT NULL DEFAULT 0,
    expenses_count           INTEGER NOT NULL DEFAULT 0,
    category_breakdown_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at               TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cashback_monthly_snapshot UNIQUE (user_id, year, month)
);

CREATE INDEX IF NOT EXISTS idx_cashback_monthly_snapshots_user_month
    ON public.cashback_monthly_snapshots (user_id, year, month);

-- =========================================================
-- project_member_settings / expense_duplicate_reports (feature_110)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.project_member_settings (
    id                      SERIAL PRIMARY KEY,
    project_id              INTEGER NOT NULL REFERENCES public.projects(project_id) ON DELETE CASCADE,
    user_id                 TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    expense_notify_mode     TEXT NOT NULL DEFAULT 'all'
                            CHECK (expense_notify_mode IN ('all', 'large_only', 'disabled')),
    large_expense_threshold NUMERIC
                            CHECK (large_expense_threshold IS NULL OR large_expense_threshold > 0),
    updated_at              TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_project_member_settings UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.expense_duplicate_reports (
    id                  SERIAL PRIMARY KEY,
    expense_id          INTEGER NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
    reported_by_user_id TEXT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    status              TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'kept', 'deleted')),
    created_at          TIMESTAMP NOT NULL DEFAULT now(),
    resolved_at         TIMESTAMP,
    resolved_by_user_id TEXT REFERENCES public.users(user_id) ON DELETE SET NULL,
    CONSTRAINT uq_expense_report_per_user UNIQUE (expense_id, reported_by_user_id)
);

CREATE INDEX IF NOT EXISTS idx_expense_duplicate_reports_expense
    ON public.expense_duplicate_reports (expense_id);
"""


def upgrade() -> None:
    op.execute(BASELINE_SQL)


def downgrade() -> None:
    # Откат baseline означал бы удаление всех таблиц вместе с данными.
    raise NotImplementedError(
        "Downgrade of the baseline migration is not supported "
        "(it would drop all tables and data)."
    )
